tap "beeftornado/rmtree"
tap "homebrew/cask-fonts"
brew "asdf"
brew "bat"
brew "cask"
brew "composer"
brew "coreutils"
brew "eza"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gh"
brew "hugo"
brew "less", link: true
brew "mas"
brew "npm"
brew "php"
brew "python"
brew "shellcheck"
brew "the_silver_searcher"
brew "rcm"
brew "vim"
brew "yarn"
brew "zsh"
cask "1password/tap/1password-cli"
cask "alfred"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "orbstack"
cask "sourcetree"
cask "spotify"
mas "Moom", id: 419330170
mas "Patterns", id: 429449079
mas "Slack", id: 803453959
