tap "beeftornado/rmtree"
tap "homebrew/cask-fonts"
brew "bat"
brew "cask"
brew "composer"
brew "coreutils"
brew "exa"
brew "git"
brew "git-delta"
brew "git-extras"
brew "gh"
brew "gnupg"
brew "gpg2"
brew "hugo"
brew "less", link: true
brew "mas"
brew "npm"
brew "php"
brew "pinentry-mac"
brew "python"
brew "shellcheck"
brew "the_silver_searcher"
brew "rcm"
brew "vim"
brew "yarn"
brew "zsh"
cask "alfred"
cask "dropbox"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "keybase"
cask "skype"
cask "sourcetree"
cask "vlc"
mas "Moom", id: 419330170
mas "Patterns", id: 429449079
mas "Slack", id: 803453959
